### ISSUE TITLE
import dll error

### ISSUE THREAD

**Issue by muhsindemir** [philippmeisberger/zfmsdk#1]
He Philipp,

Hope everything is alright for you, I try to use your lib but the dllimport code does not work.

in zfmsdk/lib/Zfm.cs

[DllImport("Zfm.dll", EntryPoint = "ZfmInitialize", CallingConvention = CallingConvention.Cdecl)]

Cant find the "Zfm.dll" could you please tell me about it

**Comment by philippmeisberger** [comment]
Hey,
great that you are trying to use it ;) The .dll needs to be compiled by yourself using Lazarus. Just open the .lpi project file from Lazarus and build it by clicking "compile" inside menu "start" on top. Write again if you have other questions or something does not work.

**Comment by muhsindemir** [comment]
He Philipp,
Thank you for answer. i compiled the .lpi via Lazaruz  and get the .dll.
I create an c# application, everything works fine but  Zfm.UpImage("fingerprint.bmp"); does not work. it thows me an exception all the time do you know about it. 
[System.Runtime.InteropServices.SEHException] = {"External component has thrown an exception."}

if you want i can share the solution

**Comment by philippmeisberger** [comment]
I guess the error occurs because you are using a relative path. Try using an absolute path.

**Comment by philippmeisberger** [comment]
Does this work?

**Comment by philippmeisberger** [comment]
Hey @muhsindemir,
I tried my best to get behind what is going wrong and opened issue #2 for that.
