### ISSUE TITLE
Using USB Interface instead of UART

### ISSUE THREAD

**Issue by TehseenHasan** [philippmeisberger/zfmsdk#3]
I want to download scanned fingerprint image using **USB interface** instead of UART because UART communication takes about 4 to 5 seconds to save Image on PC...It is very slow... So I want to use USB interface directly... How can I do this... ? I solder USB cable on USB pins of Sensor (VCC D- D+ GND) and connect sensor to my PC... Now how can I use the sensor to get fingerprint image.... Please help me

**Comment by philippmeisberger** [comment]
The only way I now is using an **USB-TTL** converter or UART directly on Rasperry Pi. Sry

**Comment by TehseenHasan** [comment]
Yes. I also use USB to TTL converter. **But this time** I want to get fingerprint image (bitmap) **quickly** but UART communication takes **4 to 5 seconds to download fingerprint image from sensor to my PC** even at **115200bps baudrate** (it is max baudrate I can set for R305 sensor or similar type of sensors)... So it is very slow protocol for real-time environment. I have to feed this fingerprint image to [SourceAFIS](https://sourceafis.machinezoo.com/) fingerprint verification library then if SourceAFIS matched the image againt previously saved fingerprints it **opens a Door**. So It is a real-time application. I cannot afford 5 seconds to wait that my fingerprint is matched or not or gate opened or not.
BTW thanks for your feedback. 👍 I think I should use USB fingerprint scanners like Digital Persona.
